version: "3.7"

services:

  web:
    build:
      context: .
      target: "web"
    container_name: "web0"

  letsencrypt:
    build:
      context: .
      target: "letsencrypt"
    container_name: "letsencrypt0"
    volumes:
      - letsencrypt_data:/etc/letsencrypt

  wproxy:
    build:
      context: .
      target: "wproxy"
    container_name: "wproxy0"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt_data:/etc/letsencrypt
    links:
      - web
      - letsencrypt 

volumes:
  letsencrypt_data:
