version: "3.3"

services:

  web:
    build:
      context: .
    image: "web"
    container_name: "web0"

  letsencrypt:
    build:
      context: .
    image: "letsencrypt"
    container_name: "letsencrypt0"
    ports:
      - "80:80"
      - "443:443"
