version: "3.7"

services:

  web:
    build:
      context: .
      target: "web"
    container_name: "web0"

  wproxy:
    build:
      context: .
      target: "wproxy"
    container_name: "wproxy0"
    ports:
      - "80:80"
    volumes:
      - letsencrypt_data:/etc/letsencrypt
    links:
      - web

  wproxy_s:
    build:
      context: .
      target: "wproxy_s"
    container_name: "wproxy_s0"
    ports:
      - "443:443"
    volumes:
      - letsencrypt_data:/etc/letsencrypt
      - html_home:/var/www/html
    links:
      - web

volumes:
  letsencrypt_data:
  html_home:
